# Generated by Django 4.2.30 on 2026-04-24 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('location_code', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('in_service', 'In Service'), ('out_of_service', 'Out of Service'), ('retired', 'Retired')], default='in_service', max_length=20)),
                ('commissioned_on', models.DateField(blank=True, null=True)),
                ('extensible_attributes', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PreventiveMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('running_hours', 'Running Hours')], default='monthly', max_length=20)),
                ('interval_value', models.IntegerField(default=1)),
                ('instructions', models.TextField(blank=True, default='')),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_plans', to='cmms.asset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReliabilityMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('mtbf_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mttr_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('availability', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('performance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reliability_metrics', to='cmms.asset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'asset', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='PermitToWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('hazards', models.JSONField(blank=True, default=list)),
                ('controls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('active', 'Active'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('approved_by_user_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmms.asset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('wo_type', models.CharField(choices=[('pm', 'Preventive'), ('cm', 'Corrective'), ('pdm', 'Predictive')], default='cm', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('ptw_reference', models.CharField(blank=True, default='', help_text='Permit-to-Work reference, if required', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('downtime_minutes', models.IntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='cmms.asset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
