# Generated by Django 4.2.30 on 2026-04-23 18:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('catalog_order', 'Catalog Order'), ('configurator_order', 'Configurator Order'), ('bom_import', 'BOM Import'), ('boq_import', 'BOQ Import'), ('rfq_spec', 'RFQ Spec'), ('contract_release', 'Contract Release'), ('forecast_plan', 'Forecast Plan')], max_length=30)),
                ('source_payload', models.JSONField(default=dict, help_text='Raw input payload from the source')),
                ('extensible_attributes', models.JSONField(blank=True, default=dict, help_text='Pack-contributed attributes')),
                ('parsed_lines', models.JSONField(blank=True, default=list, help_text='Parsed line items from the parser')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('parsed', 'Parsed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
