# Generated by Django 4.2.30 on 2026-04-24 04:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('priced', 'Priced'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('workflow_instance_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.customerrequirement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('extensible_attributes', models.JSONField(blank=True, default=dict)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quotation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('mode', models.CharField(default='discrete', help_text='Manufacturing mode: eto|discrete|process|job_shop|repetitive|mixed', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('shipped', 'Shipped'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('promised_ship_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='sales.quotation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PriceBookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(db_index=True, max_length=60)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('min_qty', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sales.pricebook')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'price_book', 'item_code', 'min_qty')},
            },
        ),
    ]
