# Generated by Django 4.2.30 on 2026-04-24 04:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_order_id', models.UUIDField(db_index=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('surveyed_at', models.DateTimeField(blank=True, null=True)),
                ('surveyor_user_id', models.UUIDField(blank=True, null=True)),
                ('findings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_order_id', models.UUIDField(db_index=True)),
                ('retention_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('release_on_milestone', models.CharField(blank=True, default='', max_length=50)),
                ('retention_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkOrderLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_order_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(db_index=True)),
                ('wbs_node_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiquidatedDamages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_order_id', models.UUIDField(db_index=True)),
                ('per_day_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cap_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesignLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_order_id', models.UUIDField(db_index=True, unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.UUIDField(blank=True, null=True)),
                ('design_snapshot', models.JSONField(blank=True, default=dict, help_text='BOM/routing/spec state at lock time')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilestoneBillingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_order_id', models.UUIDField(db_index=True)),
                ('milestone_code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_ref', models.CharField(blank=True, default='', max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'sales_order_id', 'milestone_code')},
            },
        ),
        migrations.CreateModel(
            name='ChangeOrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_order_id', models.UUIDField(db_index=True)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('cost_impact_pending', 'Cost Impact Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented'), ('cancelled', 'Cancelled')], default='submitted', max_length=30)),
                ('submitted_by', models.UUIDField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('cost_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('schedule_impact_days', models.IntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
