# Generated by Django 4.2.30 on 2026-04-24 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPCMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('characteristic', models.CharField(db_index=True, max_length=60)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('lower_spec', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('upper_spec', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('measured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('iqc', 'Incoming'), ('ipqc', 'In-Process'), ('oqc', 'Outgoing'), ('final', 'Final')], max_length=10)),
                ('reference_type', models.CharField(blank=True, default='', help_text="e.g. 'grn', 'work_order', 'shipment'", max_length=60)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('item_code', models.CharField(db_index=True, max_length=60)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_by_user_id', models.UUIDField(blank=True, null=True)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualityAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_type', models.CharField(choices=[('internal', 'Internal'), ('supplier', 'Supplier'), ('customer', 'Customer'), ('regulatory', 'Regulatory')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scope', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('reported', 'Reported'), ('closed', 'Closed')], default='planned', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonConformanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('contained', 'Contained'), ('root_caused', 'Root Caused'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quality_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncrs', to='qms.qualitycheck')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_code', models.CharField(db_index=True, max_length=60)),
                ('calibrated_on', models.DateField()),
                ('next_due_on', models.DateField()),
                ('certificate_document_id', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierCAR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('supplier_code', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('supplier_acknowledged', 'Supplier Acknowledged'), ('closed', 'Closed')], default='issued', max_length=25)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='QualityChangeControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('implemented', 'Implemented'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentControlItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('rev', models.CharField(max_length=10)),
                ('effective_from', models.DateField()),
                ('supersedes_id', models.UUIDField(blank=True, null=True)),
                ('document_store_id', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code', 'rev')},
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('root_cause', models.TextField(blank=True, default='')),
                ('corrective_action', models.TextField(blank=True, default='')),
                ('preventive_action', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('closed', 'Closed')], default='open', max_length=20)),
                ('target_close_date', models.DateField(blank=True, null=True)),
                ('ncr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='qms.nonconformancereport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
