# Generated by Django 4.2.30 on 2026-04-24 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_ref', models.CharField(max_length=120)),
                ('course_code', models.CharField(max_length=60)),
                ('completed_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SDS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('substance_code', models.CharField(db_index=True, max_length=60)),
                ('substance_name', models.CharField(max_length=255)),
                ('hazard_class', models.CharField(blank=True, default='', max_length=60)),
                ('sds_document_id', models.UUIDField(blank=True, null=True)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='ehs.sds')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PPEAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_ref', models.CharField(help_text='FK-like reference to HR employee', max_length=120)),
                ('ppe_code', models.CharField(max_length=60)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(blank=True, default='', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JSA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('steps', models.JSONField(default=list, help_text='Ordered list of {step, hazards, controls}')),
                ('approved_by_user_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HIRAEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=255)),
                ('hazard', models.CharField(max_length=255)),
                ('likelihood', models.IntegerField(help_text='1-5')),
                ('severity', models.IntegerField(help_text='1-5')),
                ('controls', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnvMonitoringReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter', models.CharField(db_index=True, max_length=60)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('limit_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('is_exceedance', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementOfChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('change_summary', models.TextField()),
                ('hira_reference_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('implemented', 'Implemented'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('occurred_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('severity', models.CharField(choices=[('near_miss', 'Near Miss'), ('first_aid', 'First Aid'), ('recordable', 'Recordable'), ('lti', 'LTI'), ('fatality', 'Fatality')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
