# Generated by Django 4.2.30 on 2026-04-23 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tenant_id', 'key', 'method', 'path')},
            },
        ),
    ]
