# Generated by Django 4.2.30 on 2026-04-23 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('checked_out_by', models.UUIDField(blank=True, null=True)),
                ('checked_out_until', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('retention_days', models.IntegerField(default=1825)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rev_number', models.IntegerField()),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('content', models.BinaryField(help_text='Stub backend; real deployments use storage_key')),
                ('storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'rev_number'],
                'unique_together': {('document', 'rev_number')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentclass'),
        ),
        migrations.CreateModel(
            name='DocumentOCRIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('extracted_text', models.TextField()),
                ('lang', models.CharField(default='eng', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_index', to='documents.documentrevision')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id'], name='documents_d_tenant__50e857_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant_id', 'status'], name='documents_d_tenant__1461e3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant_id', 'document_class'], name='documents_d_tenant__5ac7ce_idx'),
        ),
    ]
