# Generated by Django 4.2.30 on 2026-04-24 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMHeader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_item_code', models.CharField(db_index=True, max_length=60)),
                ('rev', models.CharField(default='A', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'parent_item_code', 'rev')},
            },
        ),
        migrations.CreateModel(
            name='MRPRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_number', models.CharField(db_index=True, max_length=60)),
                ('horizon_days', models.IntegerField(default=180)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('shortages_identified', models.IntegerField(default=0)),
                ('planned_orders_created', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(db_index=True, max_length=60)),
                ('order_type', models.CharField(choices=[('make', 'Make'), ('buy', 'Buy'), ('transfer', 'Transfer')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('required_by', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('mrp_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_orders', to='production_planning.mrprun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(db_index=True, max_length=60)),
                ('rev', models.CharField(default='A', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'item_code', 'rev')},
            },
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('work_center_code', models.CharField(max_length=60)),
                ('setup_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('run_minutes_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production_planning.routing')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_item_code', models.CharField(max_length=60)),
                ('quantity_per', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('scrap_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production_planning.bomheader')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('item_code', models.CharField(db_index=True, max_length=60)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('released', 'Released'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='released', max_length=20)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('planned_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='production_planning.plannedorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
