# Generated by Django 4.2.30 on 2026-04-23 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_id', models.CharField(db_index=True, help_text='Unique pack identifier from manifest', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('manifest', models.JSONField(help_text='Full parsed manifest content')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Null = global registration; set = per-tenant activation', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('pack_id', 'tenant_id')},
            },
        ),
    ]
