import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import {
  Item,
  ItemType,
  ItemStatus,
  ValuationMethod,
} from '../entities/item.entity';

@Injectable()
export class ItemSeederService implements OnModuleInit {
  private readonly logger = new Logger(ItemSeederService.name);

  constructor(
    @InjectRepository(Item)
    private readonly itemRepository: Repository<Item>,
  ) {}

  async onModuleInit(): Promise<void> {
    await this.seedItems();
  }

  async seedItems(): Promise<void> {
    this.logger.log('Seeding demo items...');

    const items = [
      // Raw Materials
      {
        itemCode: 'RM-STL-001',
        itemName: 'Steel Sheet 2mm',
        itemDescription: 'Hot rolled steel sheet, 2mm thickness, 1200x2400mm',
        itemType: ItemType.RAW_MATERIAL,
        status: ItemStatus.ACTIVE,
        category: 'RM',
        subCategory: 'Steel',
        baseUOM: 'KG',
        maintainStock: true,
        trackSerialNumber: false,
        trackBatchNumber: true,
        reorderLevel: 500,
        reorderQuantity: 2000,
        minimumOrderQuantity: 100,
        safetyStock: 200,
        leadTimeDays: 7,
        standardCost: 85.00,
        averageCost: 85.00,
        lastPurchasePrice: 84.50,
        valuationMethod: ValuationMethod.WEIGHTED_AVERAGE,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '7208',
        weight: 1,
        weightUOM: 'kg',
        isPurchased: true,
        isSold: false,
        isStockItem: true,
        preferredVendorName: 'Prime Steel Suppliers',
      },
      {
        itemCode: 'RM-ALM-001',
        itemName: 'Aluminum Rod 20mm',
        itemDescription: 'Aluminum alloy rod, 20mm diameter, 6m length',
        itemType: ItemType.RAW_MATERIAL,
        status: ItemStatus.ACTIVE,
        category: 'RM',
        subCategory: 'Aluminum',
        baseUOM: 'MTR',
        maintainStock: true,
        trackSerialNumber: false,
        trackBatchNumber: true,
        reorderLevel: 100,
        reorderQuantity: 500,
        minimumOrderQuantity: 10,
        safetyStock: 50,
        leadTimeDays: 10,
        standardCost: 320.00,
        averageCost: 318.50,
        lastPurchasePrice: 315.00,
        valuationMethod: ValuationMethod.WEIGHTED_AVERAGE,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '7604',
        weight: 0.85,
        weightUOM: 'kg',
        isPurchased: true,
        isSold: false,
        isStockItem: true,
        preferredVendorName: 'Bharat Metal Works Pvt. Ltd.',
      },
      {
        itemCode: 'RM-COP-001',
        itemName: 'Copper Wire 2.5mm',
        itemDescription: 'Pure copper wire, 2.5mm diameter, electrical grade',
        itemType: ItemType.RAW_MATERIAL,
        status: ItemStatus.ACTIVE,
        category: 'RM',
        subCategory: 'Copper',
        baseUOM: 'MTR',
        maintainStock: true,
        trackSerialNumber: false,
        trackBatchNumber: true,
        reorderLevel: 200,
        reorderQuantity: 1000,
        minimumOrderQuantity: 50,
        safetyStock: 100,
        leadTimeDays: 5,
        standardCost: 45.00,
        averageCost: 44.80,
        lastPurchasePrice: 44.50,
        valuationMethod: ValuationMethod.WEIGHTED_AVERAGE,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '7408',
        isPurchased: true,
        isSold: false,
        isStockItem: true,
      },
      // Work in Progress
      {
        itemCode: 'WIP-SFT-001',
        itemName: 'Drive Shaft Assembly (WIP)',
        itemDescription: 'Semi-finished drive shaft assembly',
        itemType: ItemType.SEMI_FINISHED,
        status: ItemStatus.ACTIVE,
        category: 'WIP',
        subCategory: 'Assemblies',
        baseUOM: 'PCS',
        maintainStock: true,
        trackSerialNumber: true,
        trackBatchNumber: false,
        reorderLevel: 20,
        reorderQuantity: 100,
        safetyStock: 10,
        standardCost: 1250.00,
        averageCost: 1245.00,
        valuationMethod: ValuationMethod.STANDARD_COST,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '8483',
        isManufactured: true,
        isPurchased: false,
        isSold: false,
        isStockItem: true,
        requiresQualityInspection: true,
      },
      {
        itemCode: 'WIP-GBX-001',
        itemName: 'Gearbox Housing (Machined)',
        itemDescription: 'Machined gearbox housing ready for assembly',
        itemType: ItemType.SEMI_FINISHED,
        status: ItemStatus.ACTIVE,
        category: 'WIP',
        subCategory: 'Housings',
        baseUOM: 'PCS',
        maintainStock: true,
        trackSerialNumber: true,
        trackBatchNumber: false,
        reorderLevel: 15,
        reorderQuantity: 50,
        safetyStock: 5,
        standardCost: 2800.00,
        averageCost: 2790.00,
        valuationMethod: ValuationMethod.STANDARD_COST,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '8483',
        isManufactured: true,
        isPurchased: false,
        isSold: false,
        isStockItem: true,
        requiresQualityInspection: true,
      },
      // Finished Goods
      {
        itemCode: 'FG-MTR-001',
        itemName: 'Industrial Motor 5HP',
        itemDescription: 'Three-phase industrial motor, 5HP, 1440 RPM',
        itemType: ItemType.FINISHED_GOOD,
        status: ItemStatus.ACTIVE,
        category: 'FG',
        subCategory: 'Motors',
        brand: 'ManufOS',
        baseUOM: 'PCS',
        maintainStock: true,
        trackSerialNumber: true,
        trackBatchNumber: false,
        reorderLevel: 10,
        reorderQuantity: 25,
        safetyStock: 5,
        leadTimeDays: 14,
        standardCost: 12500.00,
        averageCost: 12450.00,
        standardSellingPrice: 18500.00,
        minimumSellingPrice: 16000.00,
        maximumSellingPrice: 22000.00,
        valuationMethod: ValuationMethod.STANDARD_COST,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '8501',
        weight: 45,
        weightUOM: 'kg',
        isManufactured: true,
        isPurchased: false,
        isSold: true,
        allowSales: true,
        isStockItem: true,
        requiresQualityInspection: true,
        warrantyDays: 365,
      },
      {
        itemCode: 'FG-PMP-001',
        itemName: 'Centrifugal Pump CP-200',
        itemDescription: 'Industrial centrifugal pump, 200 LPM capacity',
        itemType: ItemType.FINISHED_GOOD,
        status: ItemStatus.ACTIVE,
        category: 'FG',
        subCategory: 'Pumps',
        brand: 'ManufOS',
        baseUOM: 'PCS',
        maintainStock: true,
        trackSerialNumber: true,
        trackBatchNumber: false,
        reorderLevel: 8,
        reorderQuantity: 20,
        safetyStock: 3,
        leadTimeDays: 21,
        standardCost: 8500.00,
        averageCost: 8480.00,
        standardSellingPrice: 12500.00,
        minimumSellingPrice: 11000.00,
        maximumSellingPrice: 14500.00,
        valuationMethod: ValuationMethod.STANDARD_COST,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '8413',
        weight: 28,
        weightUOM: 'kg',
        isManufactured: true,
        isPurchased: false,
        isSold: true,
        allowSales: true,
        isStockItem: true,
        requiresQualityInspection: true,
        warrantyDays: 730,
      },
      {
        itemCode: 'FG-GBX-001',
        itemName: 'Precision Gearbox PG-50',
        itemDescription: 'Precision gearbox, 50:1 ratio, 100Nm torque',
        itemType: ItemType.FINISHED_GOOD,
        status: ItemStatus.ACTIVE,
        category: 'FG',
        subCategory: 'Gearboxes',
        brand: 'ManufOS',
        baseUOM: 'PCS',
        maintainStock: true,
        trackSerialNumber: true,
        trackBatchNumber: false,
        reorderLevel: 5,
        reorderQuantity: 15,
        safetyStock: 2,
        leadTimeDays: 28,
        standardCost: 22000.00,
        averageCost: 21800.00,
        standardSellingPrice: 32000.00,
        minimumSellingPrice: 28000.00,
        maximumSellingPrice: 38000.00,
        valuationMethod: ValuationMethod.STANDARD_COST,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '8483',
        weight: 35,
        weightUOM: 'kg',
        isManufactured: true,
        isPurchased: false,
        isSold: true,
        allowSales: true,
        isStockItem: true,
        requiresQualityInspection: true,
        warrantyDays: 365,
      },
      // Spare Parts
      {
        itemCode: 'SP-BRG-001',
        itemName: 'Ball Bearing 6205',
        itemDescription: 'Deep groove ball bearing, 25x52x15mm',
        itemType: ItemType.SPARE_PART,
        status: ItemStatus.ACTIVE,
        category: 'SPARE',
        subCategory: 'Bearings',
        brand: 'SKF',
        baseUOM: 'PCS',
        maintainStock: true,
        trackSerialNumber: false,
        trackBatchNumber: true,
        reorderLevel: 50,
        reorderQuantity: 200,
        safetyStock: 20,
        leadTimeDays: 7,
        standardCost: 450.00,
        averageCost: 445.00,
        lastPurchasePrice: 440.00,
        standardSellingPrice: 650.00,
        minimumSellingPrice: 580.00,
        valuationMethod: ValuationMethod.WEIGHTED_AVERAGE,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '8482',
        isPurchased: true,
        isSold: true,
        allowSales: true,
        allowPurchase: true,
        isStockItem: true,
        preferredVendorName: 'Industrial Components Ltd.',
      },
      {
        itemCode: 'SP-SL-001',
        itemName: 'Mechanical Seal MS-40',
        itemDescription: 'Mechanical seal for pumps, 40mm shaft diameter',
        itemType: ItemType.SPARE_PART,
        status: ItemStatus.ACTIVE,
        category: 'SPARE',
        subCategory: 'Seals',
        baseUOM: 'PCS',
        maintainStock: true,
        trackSerialNumber: false,
        trackBatchNumber: true,
        reorderLevel: 30,
        reorderQuantity: 100,
        safetyStock: 15,
        leadTimeDays: 14,
        standardCost: 1200.00,
        averageCost: 1180.00,
        lastPurchasePrice: 1150.00,
        standardSellingPrice: 1800.00,
        minimumSellingPrice: 1600.00,
        valuationMethod: ValuationMethod.WEIGHTED_AVERAGE,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '8484',
        isPurchased: true,
        isSold: true,
        allowSales: true,
        allowPurchase: true,
        isStockItem: true,
      },
      {
        itemCode: 'SP-BLT-001',
        itemName: 'V-Belt A68',
        itemDescription: 'V-Belt, A section, 68 inch length',
        itemType: ItemType.SPARE_PART,
        status: ItemStatus.ACTIVE,
        category: 'SPARE',
        subCategory: 'Belts',
        baseUOM: 'PCS',
        maintainStock: true,
        trackSerialNumber: false,
        trackBatchNumber: false,
        reorderLevel: 25,
        reorderQuantity: 100,
        safetyStock: 10,
        leadTimeDays: 5,
        standardCost: 280.00,
        averageCost: 275.00,
        lastPurchasePrice: 270.00,
        standardSellingPrice: 420.00,
        minimumSellingPrice: 380.00,
        valuationMethod: ValuationMethod.WEIGHTED_AVERAGE,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '4010',
        isPurchased: true,
        isSold: true,
        allowSales: true,
        allowPurchase: true,
        isStockItem: true,
      },
      // Consumables
      {
        itemCode: 'CON-LUB-001',
        itemName: 'Industrial Lubricant Oil ISO VG 68',
        itemDescription: 'Multi-purpose industrial lubricant oil, 20L drum',
        itemType: ItemType.CONSUMABLE,
        status: ItemStatus.ACTIVE,
        category: 'CONS',
        subCategory: 'Lubricants',
        baseUOM: 'LTR',
        maintainStock: true,
        trackSerialNumber: false,
        trackBatchNumber: true,
        trackExpiryDate: true,
        reorderLevel: 200,
        reorderQuantity: 500,
        safetyStock: 100,
        leadTimeDays: 7,
        standardCost: 180.00,
        averageCost: 178.00,
        lastPurchasePrice: 175.00,
        valuationMethod: ValuationMethod.FIFO,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '2710',
        isPurchased: true,
        isSold: false,
        isStockItem: true,
        shelfLifeDays: 730,
        preferredVendorName: 'Chemical Solutions GmbH',
      },
      {
        itemCode: 'CON-CLT-001',
        itemName: 'Cutting Coolant Concentrate',
        itemDescription: 'Water-soluble cutting coolant, 25L container',
        itemType: ItemType.CONSUMABLE,
        status: ItemStatus.ACTIVE,
        category: 'CONS',
        subCategory: 'Coolants',
        baseUOM: 'LTR',
        maintainStock: true,
        trackSerialNumber: false,
        trackBatchNumber: true,
        trackExpiryDate: true,
        reorderLevel: 100,
        reorderQuantity: 300,
        safetyStock: 50,
        leadTimeDays: 7,
        standardCost: 220.00,
        averageCost: 218.00,
        lastPurchasePrice: 215.00,
        valuationMethod: ValuationMethod.FIFO,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '3403',
        isPurchased: true,
        isSold: false,
        isStockItem: true,
        shelfLifeDays: 365,
      },
      // Tools
      {
        itemCode: 'TOOL-DRL-001',
        itemName: 'HSS Drill Bit Set 1-13mm',
        itemDescription: 'High-speed steel drill bit set, 25 pieces, 1-13mm',
        itemType: ItemType.SPARE_PART,
        status: ItemStatus.ACTIVE,
        category: 'TOOL',
        subCategory: 'Drilling',
        brand: 'ProTool',
        baseUOM: 'SET',
        maintainStock: true,
        trackSerialNumber: false,
        trackBatchNumber: false,
        reorderLevel: 10,
        reorderQuantity: 30,
        safetyStock: 5,
        leadTimeDays: 14,
        standardCost: 1800.00,
        averageCost: 1780.00,
        lastPurchasePrice: 1750.00,
        standardSellingPrice: 2500.00,
        minimumSellingPrice: 2200.00,
        valuationMethod: ValuationMethod.WEIGHTED_AVERAGE,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '8207',
        isPurchased: true,
        isSold: true,
        allowSales: true,
        allowPurchase: true,
        isStockItem: true,
        preferredVendorName: 'ProTool Equipment Inc.',
      },
      {
        itemCode: 'TOOL-INS-001',
        itemName: 'Carbide Insert CNMG 120408',
        itemDescription: 'Carbide turning insert, CNMG style, 10 pack',
        itemType: ItemType.SPARE_PART,
        status: ItemStatus.ACTIVE,
        category: 'TOOL',
        subCategory: 'Inserts',
        baseUOM: 'BOX',
        maintainStock: true,
        trackSerialNumber: false,
        trackBatchNumber: true,
        reorderLevel: 20,
        reorderQuantity: 50,
        safetyStock: 10,
        leadTimeDays: 14,
        standardCost: 2200.00,
        averageCost: 2180.00,
        lastPurchasePrice: 2150.00,
        standardSellingPrice: 3200.00,
        minimumSellingPrice: 2800.00,
        valuationMethod: ValuationMethod.WEIGHTED_AVERAGE,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '8209',
        isPurchased: true,
        isSold: true,
        allowSales: true,
        allowPurchase: true,
        isStockItem: true,
        preferredVendorName: 'ProTool Equipment Inc.',
      },
      // Services
      {
        itemCode: 'SVC-MNT-001',
        itemName: 'Preventive Maintenance Service',
        itemDescription: 'Scheduled preventive maintenance service for machinery',
        itemType: ItemType.SERVICE,
        status: ItemStatus.ACTIVE,
        category: 'SVC',
        subCategory: 'Maintenance',
        baseUOM: 'PCS',
        maintainStock: false,
        trackSerialNumber: false,
        trackBatchNumber: false,
        standardCost: 5000.00,
        standardSellingPrice: 8500.00,
        minimumSellingPrice: 7000.00,
        valuationMethod: ValuationMethod.STANDARD_COST,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '998719',
        isManufactured: false,
        isPurchased: true,
        isSold: true,
        allowSales: true,
        allowPurchase: true,
        isStockItem: false,
      },
      {
        itemCode: 'SVC-CAL-001',
        itemName: 'Instrument Calibration Service',
        itemDescription: 'Calibration service for measuring instruments',
        itemType: ItemType.SERVICE,
        status: ItemStatus.ACTIVE,
        category: 'SVC',
        subCategory: 'Calibration',
        baseUOM: 'PCS',
        maintainStock: false,
        trackSerialNumber: false,
        trackBatchNumber: false,
        standardCost: 2500.00,
        standardSellingPrice: 4500.00,
        minimumSellingPrice: 3800.00,
        valuationMethod: ValuationMethod.STANDARD_COST,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '998346',
        isManufactured: false,
        isPurchased: true,
        isSold: true,
        allowSales: true,
        allowPurchase: true,
        isStockItem: false,
      },
      // Fixed Asset
      {
        itemCode: 'AST-CNC-001',
        itemName: 'CNC Milling Machine VMC-850',
        itemDescription: '3-axis CNC vertical milling machine, 850mm travel',
        itemType: ItemType.ASSET,
        status: ItemStatus.ACTIVE,
        category: 'ASSET',
        subCategory: 'CNC Machines',
        brand: 'Haas',
        baseUOM: 'PCS',
        maintainStock: true,
        trackSerialNumber: true,
        trackBatchNumber: false,
        standardCost: 4500000.00,
        averageCost: 4500000.00,
        lastPurchasePrice: 4500000.00,
        valuationMethod: ValuationMethod.STANDARD_COST,
        isTaxable: true,
        taxRate: 18,
        hsnCode: '8457',
        weight: 5500,
        weightUOM: 'kg',
        isPurchased: true,
        isSold: false,
        isStockItem: false,
        isFixedAsset: true,
        requiresQualityInspection: true,
        warrantyDays: 365,
      },
    ];

    for (const item of items) {
      try {
        const existing = await this.itemRepository.findOne({
          where: { itemCode: item.itemCode },
        });
        if (!existing) {
          await this.itemRepository.save(item);
          this.logger.log(`Created item: ${item.itemName} (${item.itemCode})`);
        }
      } catch (error) {
        this.logger.error(`Failed to seed item ${item.itemName}: ${error.message}`);
      }
    }

    this.logger.log('Demo items seeding completed');
  }
}
