import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import {
  Vendor,
  VendorType,
  VendorStatus,
  VendorRating,
} from '../entities/vendor.entity';

@Injectable()
export class VendorSeederService implements OnModuleInit {
  private readonly logger = new Logger(VendorSeederService.name);

  constructor(
    @InjectRepository(Vendor)
    private readonly vendorRepository: Repository<Vendor>,
  ) {}

  async onModuleInit(): Promise<void> {
    await this.seedVendors();
  }

  async seedVendors(): Promise<void> {
    this.logger.log('Seeding demo vendors...');

    const vendors = [
      {
        vendorCode: 'VND-001',
        vendorName: 'Prime Steel Suppliers',
        vendorType: VendorType.RAW_MATERIAL_SUPPLIER,
        status: VendorStatus.ACTIVE,
        contactPerson: 'Robert Anderson',
        email: 'randerson@primesteel.com',
        phone: '+1-555-1001',
        mobile: '+1-555-1002',
        address: '100 Steel Mill Road',
        city: 'Cleveland',
        state: 'Ohio',
        country: 'USA',
        zipCode: '44101',
        taxId: 'US-111222333',
        paymentTermsDays: 30,
        paymentTerms: 'Net 30',
        currency: 'USD',
        qualityRating: VendorRating.EXCELLENT,
        deliveryRating: VendorRating.GOOD,
        priceRating: VendorRating.GOOD,
        overallRating: VendorRating.EXCELLENT,
        onTimeDeliveryPercentage: 95.5,
        defectRate: 0.5,
        leadTimeDays: 7,
        productsSupplied: 'Steel sheets, Steel bars, Steel coils, Stainless steel',
        category: 'Raw Materials',
        isISO9001Certified: true,
        isApproved: true,
      },
      {
        vendorCode: 'VND-002',
        vendorName: 'Industrial Components Ltd.',
        vendorType: VendorType.MANUFACTURER,
        status: VendorStatus.ACTIVE,
        contactPerson: 'Jennifer White',
        email: 'jwhite@indcomponents.com',
        phone: '+1-555-2001',
        address: '250 Manufacturing Lane',
        city: 'Indianapolis',
        state: 'Indiana',
        country: 'USA',
        zipCode: '46201',
        taxId: 'US-222333444',
        paymentTermsDays: 45,
        paymentTerms: 'Net 45',
        currency: 'USD',
        qualityRating: VendorRating.GOOD,
        deliveryRating: VendorRating.GOOD,
        priceRating: VendorRating.FAIR,
        overallRating: VendorRating.GOOD,
        onTimeDeliveryPercentage: 88.0,
        defectRate: 1.2,
        leadTimeDays: 14,
        productsSupplied: 'Bearings, Gears, Shafts, Fasteners',
        category: 'Components',
        isISO9001Certified: true,
        isISO14001Certified: true,
        isApproved: true,
      },
      {
        vendorCode: 'VND-003',
        vendorName: 'ElectroTech Supplies',
        vendorType: VendorType.DISTRIBUTOR,
        status: VendorStatus.ACTIVE,
        contactPerson: 'David Lee',
        email: 'dlee@electrotech.com',
        phone: '+1-555-3001',
        mobile: '+1-555-3002',
        address: '500 Electronics Way',
        city: 'San Francisco',
        state: 'California',
        country: 'USA',
        zipCode: '94102',
        taxId: 'US-333444555',
        paymentTermsDays: 15,
        paymentTerms: 'Net 15',
        currency: 'USD',
        qualityRating: VendorRating.EXCELLENT,
        deliveryRating: VendorRating.EXCELLENT,
        priceRating: VendorRating.GOOD,
        overallRating: VendorRating.EXCELLENT,
        onTimeDeliveryPercentage: 98.0,
        defectRate: 0.2,
        leadTimeDays: 3,
        productsSupplied: 'Motors, Sensors, Controllers, Wiring, Circuit boards',
        category: 'Electronics',
        isISO9001Certified: true,
        isApproved: true,
      },
      {
        vendorCode: 'VND-004',
        vendorName: 'Bharat Metal Works Pvt. Ltd.',
        vendorType: VendorType.RAW_MATERIAL_SUPPLIER,
        status: VendorStatus.ACTIVE,
        contactPerson: 'Arun Sharma',
        email: 'asharma@bharatmetal.in',
        phone: '+91-22-44556677',
        mobile: '+91-9876543210',
        address: '12 GIDC Industrial Estate',
        city: 'Ahmedabad',
        state: 'Gujarat',
        country: 'India',
        zipCode: '382445',
        gstNumber: '24AABCB1234D1ZY',
        panNumber: 'AABCB1234D',
        paymentTermsDays: 30,
        paymentTerms: 'Net 30',
        currency: 'INR',
        qualityRating: VendorRating.GOOD,
        deliveryRating: VendorRating.FAIR,
        priceRating: VendorRating.EXCELLENT,
        overallRating: VendorRating.GOOD,
        onTimeDeliveryPercentage: 82.0,
        defectRate: 2.0,
        leadTimeDays: 10,
        productsSupplied: 'Aluminum sheets, Copper rods, Brass fittings',
        category: 'Raw Materials',
        isISO9001Certified: true,
        isApproved: true,
      },
      {
        vendorCode: 'VND-005',
        vendorName: 'ProTool Equipment Inc.',
        vendorType: VendorType.MANUFACTURER,
        status: VendorStatus.ACTIVE,
        contactPerson: 'Mark Thompson',
        email: 'mthompson@protool.com',
        phone: '+1-555-5001',
        address: '750 Tool Manufacturing Drive',
        city: 'Milwaukee',
        state: 'Wisconsin',
        country: 'USA',
        zipCode: '53201',
        taxId: 'US-555666777',
        paymentTermsDays: 30,
        paymentTerms: 'Net 30',
        currency: 'USD',
        qualityRating: VendorRating.EXCELLENT,
        deliveryRating: VendorRating.GOOD,
        priceRating: VendorRating.FAIR,
        overallRating: VendorRating.GOOD,
        onTimeDeliveryPercentage: 90.0,
        defectRate: 0.8,
        leadTimeDays: 21,
        productsSupplied: 'Cutting tools, Drill bits, Milling cutters, Measuring instruments',
        category: 'Tools',
        isISO9001Certified: true,
        isApproved: true,
      },
      {
        vendorCode: 'VND-006',
        vendorName: 'PackRight Solutions',
        vendorType: VendorType.DISTRIBUTOR,
        status: VendorStatus.ACTIVE,
        contactPerson: 'Amanda Brown',
        email: 'abrown@packright.com',
        phone: '+1-555-6001',
        address: '300 Packaging Center',
        city: 'Memphis',
        state: 'Tennessee',
        country: 'USA',
        zipCode: '38101',
        taxId: 'US-666777888',
        paymentTermsDays: 15,
        paymentTerms: 'Net 15',
        currency: 'USD',
        qualityRating: VendorRating.GOOD,
        deliveryRating: VendorRating.EXCELLENT,
        priceRating: VendorRating.EXCELLENT,
        overallRating: VendorRating.GOOD,
        onTimeDeliveryPercentage: 97.0,
        defectRate: 0.3,
        leadTimeDays: 5,
        productsSupplied: 'Cardboard boxes, Packing tape, Bubble wrap, Pallets',
        category: 'Packaging',
        isApproved: true,
      },
      {
        vendorCode: 'VND-007',
        vendorName: 'MaintainPro Services',
        vendorType: VendorType.SERVICE_PROVIDER,
        status: VendorStatus.ACTIVE,
        contactPerson: 'Kevin Martinez',
        email: 'kmartinez@maintainpro.com',
        phone: '+1-555-7001',
        mobile: '+1-555-7002',
        address: '125 Service Center Blvd',
        city: 'Houston',
        state: 'Texas',
        country: 'USA',
        zipCode: '77001',
        taxId: 'US-777888999',
        paymentTermsDays: 30,
        paymentTerms: 'Net 30',
        currency: 'USD',
        qualityRating: VendorRating.EXCELLENT,
        deliveryRating: VendorRating.EXCELLENT,
        priceRating: VendorRating.GOOD,
        overallRating: VendorRating.EXCELLENT,
        onTimeDeliveryPercentage: 99.0,
        defectRate: 0.1,
        leadTimeDays: 1,
        servicesProvided: 'Machine maintenance, Calibration, Repairs, Preventive maintenance',
        category: 'Services',
        isISO9001Certified: true,
        isApproved: true,
      },
      {
        vendorCode: 'VND-008',
        vendorName: 'Chemical Solutions GmbH',
        vendorType: VendorType.MANUFACTURER,
        status: VendorStatus.ACTIVE,
        contactPerson: 'Klaus Weber',
        email: 'kweber@chemsolutions.de',
        phone: '+49-69-11223344',
        address: 'Chemiestrasse 15',
        city: 'Frankfurt',
        state: 'Hesse',
        country: 'Germany',
        zipCode: '60311',
        taxId: 'DE987654321',
        paymentTermsDays: 45,
        paymentTerms: 'Net 45',
        currency: 'EUR',
        qualityRating: VendorRating.EXCELLENT,
        deliveryRating: VendorRating.GOOD,
        priceRating: VendorRating.FAIR,
        overallRating: VendorRating.GOOD,
        onTimeDeliveryPercentage: 85.0,
        defectRate: 0.4,
        leadTimeDays: 14,
        productsSupplied: 'Industrial lubricants, Cleaning solvents, Coolants, Adhesives',
        category: 'Consumables',
        isISO9001Certified: true,
        isISO14001Certified: true,
        isApproved: true,
      },
    ];

    for (const vendor of vendors) {
      try {
        const existing = await this.vendorRepository.findOne({
          where: { vendorCode: vendor.vendorCode },
        });
        if (!existing) {
          await this.vendorRepository.save(vendor);
          this.logger.log(`Created vendor: ${vendor.vendorName} (${vendor.vendorCode})`);
        }
      } catch (error) {
        this.logger.error(`Failed to seed vendor ${vendor.vendorName}: ${error.message}`);
      }
    }

    this.logger.log('Demo vendors seeding completed');
  }
}
