# Generated by Django 4.2.30 on 2026-04-24 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('reverse', 'Reverse')], max_length=20)),
                ('reference_type', models.CharField(blank=True, default='', help_text='sales_order / purchase_order / rma', max_length=60)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('carrier_code', models.CharField(blank=True, default='', max_length=60)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('picked', 'Picked'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('exception', 'Exception'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=60)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('connector_id', models.CharField(blank=True, default='', help_text="Matches an integration.Connector's connector_id", max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
