# Generated by Django 4.2.30 on 2026-04-23 18:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPackActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_id', models.CharField(db_index=True, max_length=100)),
                ('pack_version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_activations', to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'pack_id')},
            },
        ),
    ]
