# Generated by Django 4.2.30 on 2026-04-24 04:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Canonical bin code, e.g. 'A01-R03-L02-P05'", max_length=80)),
                ('aisle', models.CharField(blank=True, default='', max_length=20)),
                ('rack', models.CharField(blank=True, default='', max_length=20)),
                ('level', models.CharField(blank=True, default='', max_length=20)),
                ('position', models.CharField(blank=True, default='', max_length=20)),
                ('zone', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('capacity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('full', 'Full')], default='active', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RFTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('putaway', 'Putaway'), ('pick', 'Pick'), ('move', 'Move'), ('count', 'Count')], max_length=20)),
                ('item_code', models.CharField(max_length=60)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assigned_to_user_id', models.UUIDField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_tasks', to='wms.bin')),
                ('target_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_tasks', to='wms.bin')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bin',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='wms.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='bin',
            unique_together={('tenant', 'warehouse', 'code')},
        ),
    ]
