# Generated by Django 4.2.30 on 2026-04-24 04:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('uom', models.CharField(default='EA', max_length=20)),
                ('item_class', models.CharField(choices=[('raw', 'Raw Material'), ('wip', 'WIP'), ('finished', 'Finished Good'), ('service', 'Service')], default='raw', max_length=20)),
                ('tracking', models.CharField(choices=[('none', 'None'), ('lot', 'Lot'), ('batch', 'Batch'), ('serial', 'Serial')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('extensible_attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(db_index=True, max_length=100)),
                ('tracking', models.CharField(choices=[('lot', 'Lot'), ('batch', 'Batch'), ('serial', 'Serial')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('location_code', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('quarantine', 'Quarantine'), ('consumed', 'Consumed'), ('scrapped', 'Scrapped')], default='available', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_units', to='inventory.item')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.stockunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'item', 'identifier')},
            },
        ),
    ]
