# Generated by Django 4.2.30 on 2026-04-23 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Null = core template (fallback)', null=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-App Inbox')], max_length=20)),
                ('locale', models.CharField(default='en-US', max_length=10)),
                ('version', models.IntegerField(default=1)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('is_transactional', models.BooleanField(default=False, help_text='Transactional templates bypass user opt-out preferences.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'channel', 'locale', 'is_active'], name='notificatio_event_t_067fc8_idx')],
                'unique_together': {('tenant_id', 'event_type', 'channel', 'locale', 'version')},
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-App Inbox')], max_length=20)),
                ('event_type', models.CharField(help_text="Use '*' to opt out of all", max_length=100)),
                ('opted_in', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_id', 'tenant_id', 'channel', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('recipient_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('recipient_address', models.CharField(blank=True, default='', help_text='Email address, phone, device token, …', max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-App Inbox')], max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('locale', models.CharField(default='en-US', max_length=10)),
                ('rendered_subject', models.CharField(blank=True, default='', max_length=255)),
                ('rendered_body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('suppressed', 'Suppressed by opt-out')], default='queued', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('template_version', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='notificatio_tenant__dc2cb7_idx'), models.Index(fields=['event_type', 'status'], name='notificatio_event_t_9b15bd_idx')],
            },
        ),
    ]
