# Generated by Django 4.2.30 on 2026-04-24 04:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoughCutCapacityPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_index=True)),
                ('resource_code', models.CharField(max_length=60)),
                ('required_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsensusRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_name', models.CharField(max_length=120)),
                ('forecast_version', models.IntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked')], default='open', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ATPQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_requirement_id', models.UUIDField()),
                ('promise_date', models.DateField()),
                ('promise_qty', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_ctp', models.BooleanField(default=False, help_text='True = capable-to-promise (plan+make)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterProductionSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_index=True)),
                ('item_code', models.CharField(db_index=True, max_length=60)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('frozen', 'Frozen')], default='proposed', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'period_start', 'item_code')},
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_index=True)),
                ('item_code', models.CharField(db_index=True, max_length=60)),
                ('forecast_qty', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('method', models.CharField(choices=[('moving_average', 'Moving Average'), ('exp_smoothing', 'Exponential Smoothing'), ('consensus', 'Consensus'), ('manual', 'Manual')], default='moving_average', max_length=30)),
                ('confidence', models.FloatField(default=0.5)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'period_start', 'item_code', 'version')},
            },
        ),
    ]
