# Generated by Django 4.2.30 on 2026-04-23 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(db_index=True, max_length=100)),
                ('definition_version', models.CharField(max_length=50)),
                ('resolved_definition', models.JSONField(help_text='Core + pack insertions merged at start; never mutated thereafter')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('current_step', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('history', models.JSONField(default=list, help_text='Ordered list of transition records')),
                ('context', models.JSONField(default=dict, help_text='Mutable state carried through the instance')),
                ('active_packs', models.JSONField(default=list, help_text='Pack ids active at start')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInsertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(db_index=True, max_length=100)),
                ('pack_id', models.CharField(db_index=True, max_length=100)),
                ('insertion_point', models.CharField(max_length=100)),
                ('step', models.JSONField(help_text='Step JSON to splice in at the insertion point')),
                ('load_order', models.IntegerField(default=0, help_text='Lower runs first among co-located insertions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['load_order'],
                'unique_together': {('workflow_id', 'pack_id', 'insertion_point')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(db_index=True, max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('owner', models.CharField(default='core', help_text="'core' or a pack_id", max_length=100)),
                ('definition', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['workflow_id', 'is_active'], name='workflow_wo_workflo_923711_idx')],
                'unique_together': {('workflow_id', 'version')},
            },
        ),
    ]
