# Generated by Django 4.2.30 on 2026-04-23 18:06

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('actor', models.CharField(blank=True, default='system', max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('entity_type', models.CharField(db_index=True, max_length=255)),
                ('entity_id', models.CharField(db_index=True, max_length=255)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('reason_for_change', models.TextField(blank=True, default='')),
                ('layer', models.CharField(default='core', max_length=50)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('this_hash', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'timestamp'], name='audit_audit_entity__99ee0b_idx')],
            },
        ),
    ]
