# Generated by Django 4.2.30 on 2026-04-23 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('record_count', models.IntegerField()),
                ('from_timestamp', models.DateTimeField()),
                ('to_timestamp', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditReaderGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('granted_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Moved to archive tier after 5 years online'),
        ),
        migrations.AddIndex(
            model_name='auditrecord',
            index=models.Index(fields=['tenant_id', 'is_archived'], name='audit_audit_tenant__6e1e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditrecord',
            index=models.Index(condition=models.Q(('reason_for_change', '')), fields=['tenant_id'], name='audit_nullreason_idx'),
        ),
        migrations.AddField(
            model_name='auditreadergrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='auditreadergrant',
            unique_together={('tenant_id', 'user')},
        ),
    ]
