# Generated by Django 4.2.30 on 2026-04-23 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='is_delegated_admin',
            field=models.BooleanField(default=False, help_text='Whether this user can manage other users in this tenant'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=50),
        ),
        migrations.CreateModel(
            name='MFAConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, default='', max_length=64)),
                ('backup_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ABACPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('resource_type', models.CharField(help_text="e.g. 'sales.customerrequirement'", max_length=100)),
                ('action', models.CharField(help_text="e.g. 'create', 'read', 'update', 'delete'", max_length=50)),
                ('conditions', models.JSONField(default=dict, help_text='JSON conditions evaluated against request context')),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=10)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority policies are evaluated first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null = global policy; set = tenant-specific', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abac_policies', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
