# Generated by Django 4.2.30 on 2026-04-24 04:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(db_index=True, max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('uom', models.CharField(default='EA', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('extensible_attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'part_number')},
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('released', 'Released'), ('implemented', 'Implemented'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('target_release_date', models.DateField(blank=True, null=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_orders', to='plm.changerequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_notices', to='plm.changeorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rev_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('drawing_document_id', models.UUIDField(blank=True, help_text='Link to documents.Document', null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='plm.part')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'part', 'rev_code')},
            },
        ),
    ]
