import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';

export enum AlertType {
  QUALITY_ISSUE = 'Quality Issue',
  SPECIFICATION_DEVIATION = 'Specification Deviation',
  NCR_THRESHOLD = 'NCR Threshold',
  DEFECT_RATE = 'Defect Rate',
  SPC_VIOLATION = 'SPC Violation',
  INSPECTION_OVERDUE = 'Inspection Overdue',
  CAPA_OVERDUE = 'CAPA Overdue',
  SUPPLIER_QUALITY = 'Supplier Quality',
  CUSTOMER_COMPLAINT = 'Customer Complaint',
  AUDIT_FINDING = 'Audit Finding',
  CRITICAL_DEFECT = 'Critical Defect',
  TREND_ALERT = 'Trend Alert',
  PROCESS_OUT_OF_CONTROL = 'Process Out of Control',
  OTHER = 'Other',
}

export enum AlertSeverity {
  LOW = 'Low',
  MEDIUM = 'Medium',
  HIGH = 'High',
  CRITICAL = 'Critical',
}

export enum AlertStatus {
  NEW = 'New',
  ACKNOWLEDGED = 'Acknowledged',
  INVESTIGATING = 'Investigating',
  ACTION_REQUIRED = 'Action Required',
  IN_PROGRESS = 'In Progress',
  RESOLVED = 'Resolved',
  CLOSED = 'Closed',
  DISMISSED = 'Dismissed',
}

@Entity('quality_alerts')
export class QualityAlert {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ unique: true, length: 50 })
  alertNumber: string;

  @Column({ length: 255 })
  title: string;

  @Column({ type: 'text' })
  description: string;

  @Column({ type: 'enum', enum: AlertType, default: AlertType.QUALITY_ISSUE })
  alertType: AlertType;

  @Column({ type: 'enum', enum: AlertSeverity, default: AlertSeverity.MEDIUM })
  severity: AlertSeverity;

  @Column({ type: 'enum', enum: AlertStatus, default: AlertStatus.NEW })
  status: AlertStatus;

  // Source reference
  @Column({ length: 255, nullable: true })
  sourceType: string; // Inspection, NCR, CAPA, SPC, Audit, etc.

  @Column({ nullable: true })
  sourceId: string;

  @Column({ length: 100, nullable: true })
  sourceReference: string;

  @Column({ nullable: true })
  inspectionId: string;

  @Column({ length: 100, nullable: true })
  inspectionNumber: string;

  @Column({ nullable: true })
  ncrId: string;

  @Column({ length: 100, nullable: true })
  ncrNumber: string;

  @Column({ nullable: true })
  capaId: string;

  @Column({ length: 100, nullable: true })
  capaNumber: string;

  // Item/Product
  @Column({ nullable: true })
  itemId: string;

  @Column({ length: 100, nullable: true })
  itemCode: string;

  @Column({ length: 255, nullable: true })
  itemName: string;

  @Column({ length: 100, nullable: true })
  batchNumber: string;

  @Column({ length: 100, nullable: true })
  lotNumber: string;

  // Location
  @Column({ nullable: true })
  departmentId: string;

  @Column({ length: 255, nullable: true })
  departmentName: string;

  @Column({ nullable: true })
  workCenterId: string;

  @Column({ length: 100, nullable: true })
  workCenterCode: string;

  @Column({ nullable: true })
  warehouseId: string;

  @Column({ length: 100, nullable: true })
  warehouseName: string;

  @Column({ length: 255, nullable: true })
  location: string;

  // Trigger information
  @Column({ type: 'text', nullable: true })
  triggerCondition: string;

  @Column({ type: 'decimal', precision: 15, scale: 4, nullable: true })
  thresholdValue: number;

  @Column({ type: 'decimal', precision: 15, scale: 4, nullable: true })
  actualValue: number;

  @Column({ type: 'decimal', precision: 5, scale: 2, nullable: true })
  deviationPercentage: number;

  // Alert details
  @Column({ type: 'text', nullable: true })
  impactAssessment: string;

  @Column({ type: 'text', nullable: true })
  recommendedActions: string;

  @Column({ type: 'date' })
  alertDate: Date;

  @Column({ type: 'timestamp' })
  alertTime: Date;

  @Column({ type: 'date', nullable: true })
  dueDate: Date;

  // Parties involved
  @Column({ nullable: true })
  generatedById: string;

  @Column({ length: 255, nullable: true })
  generatedByName: string;

  @Column({ default: true })
  isAutoGenerated: boolean;

  @Column({ nullable: true })
  assignedToId: string;

  @Column({ length: 255, nullable: true })
  assignedToName: string;

  @Column({ type: 'date', nullable: true })
  assignedDate: Date;

  // Notification
  @Column({ type: 'json', nullable: true })
  notificationEmails: string[];

  @Column({ type: 'json', nullable: true })
  notifiedUsers: string[];

  @Column({ type: 'timestamp', nullable: true })
  firstNotificationSent: Date;

  @Column({ type: 'timestamp', nullable: true })
  lastNotificationSent: Date;

  @Column({ type: 'int', default: 0 })
  notificationCount: number;

  @Column({ default: false })
  requiresEscalation: boolean;

  @Column({ default: false })
  isEscalated: boolean;

  @Column({ type: 'timestamp', nullable: true })
  escalatedAt: Date;

  @Column({ length: 255, nullable: true })
  escalatedTo: string;

  // Response
  @Column({ length: 255, nullable: true })
  acknowledgedBy: string;

  @Column({ type: 'timestamp', nullable: true })
  acknowledgedAt: Date;

  @Column({ type: 'text', nullable: true })
  investigationNotes: string;

  @Column({ type: 'text', nullable: true })
  resolution: string;

  @Column({ type: 'text', nullable: true })
  actionsTaken: string;

  @Column({ length: 255, nullable: true })
  resolvedBy: string;

  @Column({ type: 'timestamp', nullable: true })
  resolvedAt: Date;

  // Follow-up actions
  @Column({ default: false })
  ncrGenerated: boolean;

  @Column({ nullable: true })
  generatedNcrId: string;

  @Column({ length: 100, nullable: true })
  generatedNcrNumber: string;

  @Column({ default: false })
  capaGenerated: boolean;

  @Column({ nullable: true })
  generatedCapaId: string;

  @Column({ length: 100, nullable: true })
  generatedCapaNumber: string;

  @Column({ default: false })
  inspectionTriggered: boolean;

  @Column({ nullable: true })
  triggeredInspectionId: string;

  @Column({ length: 100, nullable: true })
  triggeredInspectionNumber: string;

  // Metrics
  @Column({ type: 'int', nullable: true })
  responseTimeMinutes: number;

  @Column({ type: 'int', nullable: true })
  resolutionTimeHours: number;

  @Column({ default: false })
  isOverdue: boolean;

  // Workflow
  @Column({ length: 100, nullable: true })
  closedBy: string;

  @Column({ type: 'timestamp', nullable: true })
  closedAt: Date;

  @Column({ length: 100, nullable: true })
  dismissedBy: string;

  @Column({ type: 'timestamp', nullable: true })
  dismissedAt: Date;

  @Column({ type: 'text', nullable: true })
  dismissalReason: string;

  // Attachments
  @Column({ type: 'json', nullable: true })
  attachments: {
    fileName: string;
    fileUrl: string;
    fileType: string;
    uploadedBy: string;
    uploadedAt: Date;
  }[];

  // Additional
  @Column({ type: 'text', nullable: true })
  notes: string;

  @Column({ type: 'json', nullable: true })
  customFields: Record<string, any>;

  // Metadata
  @Column({ nullable: true, length: 100 })
  createdBy: string;

  @Column({ nullable: true, length: 100 })
  updatedBy: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
