# Generated by Django 4.2.30 on 2026-04-24 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('plc_endpoint', models.CharField(blank=True, default='', help_text='opc.tcp:// or modbus:// endpoint; empty if manual', max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_number', models.CharField(db_index=True, max_length=60)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('produced_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('scrap_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='scheduled', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='mes.workcenter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OEESnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('availability', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('performance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oee_snapshots', to='mes.workcenter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AndonEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('quality', 'Quality'), ('maintenance', 'Maintenance'), ('material', 'Material'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andon_events', to='mes.workcenter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
