# Generated by Django 4.2.30 on 2026-04-23 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('view_name', models.CharField(max_length=255)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('cron_expression', models.CharField(help_text='Standard 5-field cron spec; interpreted by the beat runner.', max_length=100)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], default='csv', max_length=10)),
                ('delivery_channel', models.CharField(default='email', help_text='Channel used by the Notification service for delivery.', max_length=20)),
                ('delivery_recipient', models.CharField(help_text='Email / phone / address forwarded to the Notification service.', max_length=255)),
                ('notification_event_type', models.CharField(default='report.scheduled_delivery', help_text='Event type used to resolve a notification template.', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
