import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Holiday, HolidayStatus, HolidayType } from '../entities/holiday.entity';

@Injectable()
export class HolidaySeederService implements OnModuleInit {
  private readonly logger = new Logger(HolidaySeederService.name);

  constructor(
    @InjectRepository(Holiday)
    private readonly holidayRepository: Repository<Holiday>,
  ) {}

  async onModuleInit(): Promise<void> {
    await this.seedHolidays();
  }

  async seedHolidays(): Promise<void> {
    this.logger.log('Seeding holidays...');

    const holidays2025 = [
      // 2025 Holidays
      {
        name: 'Republic Day',
        date: new Date('2025-01-26'),
        type: HolidayType.PUBLIC,
        description: 'Celebrates the adoption of the Constitution of India.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Maha Shivaratri',
        date: new Date('2025-02-26'),
        type: HolidayType.RESTRICTED,
        description: 'Hindu festival dedicated to Lord Shiva.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Holi',
        date: new Date('2025-03-14'),
        type: HolidayType.PUBLIC,
        description: 'Festival of colors celebrating the victory of good over evil.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Good Friday',
        date: new Date('2025-04-18'),
        type: HolidayType.PUBLIC,
        description: 'Christian holiday commemorating the crucifixion of Jesus Christ.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Ram Navami',
        date: new Date('2025-04-06'),
        type: HolidayType.RESTRICTED,
        description: 'Hindu festival celebrating the birth of Lord Rama.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Mahavir Jayanti',
        date: new Date('2025-04-10'),
        type: HolidayType.RESTRICTED,
        description: 'Jain festival celebrating the birth of Lord Mahavira.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Buddha Purnima',
        date: new Date('2025-05-12'),
        type: HolidayType.RESTRICTED,
        description: 'Buddhist holiday celebrating the birth of Gautama Buddha.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Eid ul-Fitr',
        date: new Date('2025-03-31'),
        type: HolidayType.RESTRICTED,
        description: 'Islamic festival marking the end of Ramadan.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Eid ul-Adha',
        date: new Date('2025-06-07'),
        type: HolidayType.RESTRICTED,
        description: 'Islamic festival of sacrifice.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Independence Day',
        date: new Date('2025-08-15'),
        type: HolidayType.PUBLIC,
        description: 'Celebrates India\'s independence from British rule in 1947.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Janmashtami',
        date: new Date('2025-08-16'),
        type: HolidayType.RESTRICTED,
        description: 'Hindu festival celebrating the birth of Lord Krishna.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Muharram',
        date: new Date('2025-07-06'),
        type: HolidayType.RESTRICTED,
        description: 'Islamic New Year.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Gandhi Jayanti',
        date: new Date('2025-10-02'),
        type: HolidayType.PUBLIC,
        description: 'Birthday of Mahatma Gandhi, Father of the Nation.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Dussehra',
        date: new Date('2025-10-02'),
        type: HolidayType.PUBLIC,
        description: 'Hindu festival celebrating victory of good over evil.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Diwali',
        date: new Date('2025-10-20'),
        type: HolidayType.PUBLIC,
        description: 'Festival of lights, one of the most significant Hindu festivals.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Guru Nanak Jayanti',
        date: new Date('2025-11-05'),
        type: HolidayType.RESTRICTED,
        description: 'Sikh festival celebrating the birth of Guru Nanak.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Christmas',
        date: new Date('2025-12-25'),
        type: HolidayType.PUBLIC,
        description: 'Christian holiday celebrating the birth of Jesus Christ.',
        isPaid: true,
        numberOfDays: 1,
        year: 2025,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
    ];

    const holidays2026 = [
      // 2026 Holidays
      {
        name: 'Republic Day',
        date: new Date('2026-01-26'),
        type: HolidayType.PUBLIC,
        description: 'Celebrates the adoption of the Constitution of India.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Maha Shivaratri',
        date: new Date('2026-02-15'),
        type: HolidayType.RESTRICTED,
        description: 'Hindu festival dedicated to Lord Shiva.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Holi',
        date: new Date('2026-03-04'),
        type: HolidayType.PUBLIC,
        description: 'Festival of colors celebrating the victory of good over evil.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Ram Navami',
        date: new Date('2026-03-26'),
        type: HolidayType.RESTRICTED,
        description: 'Hindu festival celebrating the birth of Lord Rama.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Mahavir Jayanti',
        date: new Date('2026-03-29'),
        type: HolidayType.RESTRICTED,
        description: 'Jain festival celebrating the birth of Lord Mahavira.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Good Friday',
        date: new Date('2026-04-03'),
        type: HolidayType.PUBLIC,
        description: 'Christian holiday commemorating the crucifixion of Jesus Christ.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Eid ul-Fitr',
        date: new Date('2026-03-20'),
        type: HolidayType.RESTRICTED,
        description: 'Islamic festival marking the end of Ramadan.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Buddha Purnima',
        date: new Date('2026-05-01'),
        type: HolidayType.RESTRICTED,
        description: 'Buddhist holiday celebrating the birth of Gautama Buddha.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Eid ul-Adha',
        date: new Date('2026-05-27'),
        type: HolidayType.RESTRICTED,
        description: 'Islamic festival of sacrifice.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Muharram',
        date: new Date('2026-06-26'),
        type: HolidayType.RESTRICTED,
        description: 'Islamic New Year.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Janmashtami',
        date: new Date('2026-08-06'),
        type: HolidayType.RESTRICTED,
        description: 'Hindu festival celebrating the birth of Lord Krishna.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Independence Day',
        date: new Date('2026-08-15'),
        type: HolidayType.PUBLIC,
        description: 'Celebrates India\'s independence from British rule in 1947.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Milad un-Nabi',
        date: new Date('2026-09-05'),
        type: HolidayType.RESTRICTED,
        description: 'Islamic holiday celebrating the birthday of Prophet Muhammad.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Gandhi Jayanti',
        date: new Date('2026-10-02'),
        type: HolidayType.PUBLIC,
        description: 'Birthday of Mahatma Gandhi, Father of the Nation.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Dussehra',
        date: new Date('2026-10-20'),
        type: HolidayType.PUBLIC,
        description: 'Hindu festival celebrating victory of good over evil.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Diwali',
        date: new Date('2026-11-08'),
        type: HolidayType.PUBLIC,
        description: 'Festival of lights, one of the most significant Hindu festivals.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Guru Nanak Jayanti',
        date: new Date('2026-11-24'),
        type: HolidayType.RESTRICTED,
        description: 'Sikh festival celebrating the birth of Guru Nanak.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        name: 'Christmas',
        date: new Date('2026-12-25'),
        type: HolidayType.PUBLIC,
        description: 'Christian holiday celebrating the birth of Jesus Christ.',
        isPaid: true,
        numberOfDays: 1,
        year: 2026,
        status: HolidayStatus.ACTIVE,
        createdBy: 'system',
      },
    ];

    const allHolidays = [...holidays2025, ...holidays2026];

    for (const holiday of allHolidays) {
      try {
        const existing = await this.holidayRepository.findOne({
          where: {
            name: holiday.name,
            year: holiday.year,
          },
        });
        if (!existing) {
          await this.holidayRepository.save(holiday);
          this.logger.log(`Created holiday: ${holiday.name} (${holiday.year})`);
        }
      } catch (error) {
        this.logger.error(`Failed to seed holiday ${holiday.name}: ${error.message}`);
      }
    }

    this.logger.log('Holidays seeding completed');
  }
}
