import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { LeaveType, LeaveTypeStatus, LeaveAccrualType } from '../entities/leave-type.entity';

@Injectable()
export class LeaveTypeSeederService implements OnModuleInit {
  private readonly logger = new Logger(LeaveTypeSeederService.name);

  constructor(
    @InjectRepository(LeaveType)
    private readonly leaveTypeRepository: Repository<LeaveType>,
  ) {}

  async onModuleInit(): Promise<void> {
    await this.seedLeaveTypes();
  }

  async seedLeaveTypes(): Promise<void> {
    this.logger.log('Seeding leave types...');

    const leaveTypes = [
      {
        code: 'CL',
        name: 'Casual Leave',
        description: 'Leave for personal reasons, emergencies, or short-term requirements. Can be taken for a minimum of half day.',
        isPaid: true,
        maxDaysPerYear: 12,
        minDaysPerApplication: 0.5,
        maxDaysPerApplication: 3,
        maxCarryForward: 0,
        allowCarryForward: false,
        allowEncashment: false,
        maxEncashmentDays: 0,
        requiresApproval: true,
        requiresDocument: false,
        minAdvanceNoticeDays: 0,
        maxBackdatedDays: 3,
        accrualType: LeaveAccrualType.MONTHLY,
        accrualRate: 1,
        allowHalfDay: true,
        allowNegativeBalance: false,
        includeHolidays: false,
        includeWeekends: false,
        applicableAfterMonths: 0,
        displayOrder: 1,
        color: '#3B82F6',
        status: LeaveTypeStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        code: 'SL',
        name: 'Sick Leave',
        description: 'Leave for medical reasons, illness, or health-related issues. Medical certificate required for more than 2 consecutive days.',
        isPaid: true,
        maxDaysPerYear: 12,
        minDaysPerApplication: 0.5,
        maxDaysPerApplication: 7,
        maxCarryForward: 0,
        allowCarryForward: false,
        allowEncashment: false,
        maxEncashmentDays: 0,
        requiresApproval: true,
        requiresDocument: true,
        minAdvanceNoticeDays: 0,
        maxBackdatedDays: 7,
        accrualType: LeaveAccrualType.MONTHLY,
        accrualRate: 1,
        allowHalfDay: true,
        allowNegativeBalance: false,
        includeHolidays: false,
        includeWeekends: false,
        applicableAfterMonths: 0,
        displayOrder: 2,
        color: '#EF4444',
        status: LeaveTypeStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        code: 'EL',
        name: 'Earned Leave',
        description: 'Annual leave earned based on service. Can be accumulated and encashed. Must be planned in advance.',
        isPaid: true,
        maxDaysPerYear: 15,
        minDaysPerApplication: 1,
        maxDaysPerApplication: 15,
        maxCarryForward: 30,
        allowCarryForward: true,
        allowEncashment: true,
        maxEncashmentDays: 15,
        requiresApproval: true,
        requiresDocument: false,
        minAdvanceNoticeDays: 7,
        maxBackdatedDays: 0,
        accrualType: LeaveAccrualType.MONTHLY,
        accrualRate: 1.25,
        allowHalfDay: false,
        allowNegativeBalance: false,
        includeHolidays: true,
        includeWeekends: true,
        applicableAfterMonths: 12,
        displayOrder: 3,
        color: '#10B981',
        status: LeaveTypeStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        code: 'ML',
        name: 'Maternity Leave',
        description: 'Leave for female employees before and after childbirth as per Maternity Benefit Act. Applicable for up to two surviving children.',
        isPaid: true,
        maxDaysPerYear: 180,
        minDaysPerApplication: 1,
        maxDaysPerApplication: 180,
        maxCarryForward: 0,
        allowCarryForward: false,
        allowEncashment: false,
        maxEncashmentDays: 0,
        requiresApproval: true,
        requiresDocument: true,
        minAdvanceNoticeDays: 30,
        maxBackdatedDays: 0,
        accrualType: LeaveAccrualType.NONE,
        accrualRate: 0,
        allowHalfDay: false,
        allowNegativeBalance: false,
        includeHolidays: true,
        includeWeekends: true,
        applicableGenders: ['Female'],
        applicableAfterMonths: 0,
        displayOrder: 4,
        color: '#EC4899',
        status: LeaveTypeStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        code: 'PL',
        name: 'Paternity Leave',
        description: 'Leave for male employees to care for their newborn child and support the mother. Must be taken within 6 months of childbirth.',
        isPaid: true,
        maxDaysPerYear: 15,
        minDaysPerApplication: 1,
        maxDaysPerApplication: 15,
        maxCarryForward: 0,
        allowCarryForward: false,
        allowEncashment: false,
        maxEncashmentDays: 0,
        requiresApproval: true,
        requiresDocument: true,
        minAdvanceNoticeDays: 7,
        maxBackdatedDays: 0,
        accrualType: LeaveAccrualType.NONE,
        accrualRate: 0,
        allowHalfDay: false,
        allowNegativeBalance: false,
        includeHolidays: true,
        includeWeekends: true,
        applicableGenders: ['Male'],
        applicableAfterMonths: 0,
        displayOrder: 5,
        color: '#8B5CF6',
        status: LeaveTypeStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        code: 'LWP',
        name: 'Leave Without Pay',
        description: 'Unpaid leave when all other leave types are exhausted or for extended personal requirements.',
        isPaid: false,
        maxDaysPerYear: 365,
        minDaysPerApplication: 1,
        maxDaysPerApplication: 30,
        maxCarryForward: 0,
        allowCarryForward: false,
        allowEncashment: false,
        maxEncashmentDays: 0,
        requiresApproval: true,
        requiresDocument: false,
        minAdvanceNoticeDays: 3,
        maxBackdatedDays: 0,
        accrualType: LeaveAccrualType.NONE,
        accrualRate: 0,
        allowHalfDay: true,
        allowNegativeBalance: true,
        includeHolidays: true,
        includeWeekends: true,
        applicableAfterMonths: 0,
        displayOrder: 6,
        color: '#6B7280',
        status: LeaveTypeStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        code: 'COMP',
        name: 'Compensatory Off',
        description: 'Leave earned for working on holidays or weekends. Must be availed within 30 days of earning.',
        isPaid: true,
        maxDaysPerYear: 12,
        minDaysPerApplication: 0.5,
        maxDaysPerApplication: 2,
        maxCarryForward: 0,
        allowCarryForward: false,
        allowEncashment: false,
        maxEncashmentDays: 0,
        requiresApproval: true,
        requiresDocument: false,
        minAdvanceNoticeDays: 1,
        maxBackdatedDays: 0,
        accrualType: LeaveAccrualType.NONE,
        accrualRate: 0,
        allowHalfDay: true,
        allowNegativeBalance: false,
        includeHolidays: false,
        includeWeekends: false,
        applicableAfterMonths: 0,
        displayOrder: 7,
        color: '#F59E0B',
        status: LeaveTypeStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        code: 'BL',
        name: 'Bereavement Leave',
        description: 'Leave granted in case of death of immediate family members (spouse, children, parents, siblings).',
        isPaid: true,
        maxDaysPerYear: 5,
        minDaysPerApplication: 1,
        maxDaysPerApplication: 5,
        maxCarryForward: 0,
        allowCarryForward: false,
        allowEncashment: false,
        maxEncashmentDays: 0,
        requiresApproval: true,
        requiresDocument: true,
        minAdvanceNoticeDays: 0,
        maxBackdatedDays: 3,
        accrualType: LeaveAccrualType.NONE,
        accrualRate: 0,
        allowHalfDay: false,
        allowNegativeBalance: false,
        includeHolidays: true,
        includeWeekends: true,
        applicableAfterMonths: 0,
        displayOrder: 8,
        color: '#1F2937',
        status: LeaveTypeStatus.ACTIVE,
        createdBy: 'system',
      },
      {
        code: 'WFH',
        name: 'Work From Home',
        description: 'Permission to work from home for specific days. Not a leave type but recorded for attendance purposes.',
        isPaid: true,
        maxDaysPerYear: 52,
        minDaysPerApplication: 1,
        maxDaysPerApplication: 5,
        maxCarryForward: 0,
        allowCarryForward: false,
        allowEncashment: false,
        maxEncashmentDays: 0,
        requiresApproval: true,
        requiresDocument: false,
        minAdvanceNoticeDays: 1,
        maxBackdatedDays: 0,
        accrualType: LeaveAccrualType.NONE,
        accrualRate: 0,
        allowHalfDay: false,
        allowNegativeBalance: false,
        includeHolidays: false,
        includeWeekends: false,
        applicableAfterMonths: 3,
        displayOrder: 9,
        color: '#0EA5E9',
        status: LeaveTypeStatus.ACTIVE,
        createdBy: 'system',
      },
    ];

    for (const leaveType of leaveTypes) {
      try {
        const existing = await this.leaveTypeRepository.findOne({
          where: { code: leaveType.code },
        });
        if (!existing) {
          await this.leaveTypeRepository.save(leaveType);
          this.logger.log(`Created leave type: ${leaveType.name}`);
        }
      } catch (error) {
        this.logger.error(`Failed to seed leave type ${leaveType.name}: ${error.message}`);
      }
    }

    this.logger.log('Leave types seeding completed');
  }
}
