# Generated by Django 4.2.30 on 2026-04-24 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantpackactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledBaseUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('item_code', models.CharField(max_length=60)),
                ('customer_account_id', models.UUIDField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('lost', 'Lost')], default='active', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='ServiceDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('scheduled_at', models.DateTimeField()),
                ('technician_user_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('en_route', 'En Route'), ('on_site', 'On Site'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('installed_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='field_service.installedbaseunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('customer_account_id', models.UUIDField()),
                ('contract_type', models.CharField(choices=[('amc', 'AMC'), ('sla', 'SLA'), ('warranty', 'Warranty')], default='amc', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('response_sla_hours', models.IntegerField(blank=True, null=True)),
                ('resolution_sla_hours', models.IntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('installed_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmas', to='field_service.installedbaseunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'number')},
            },
        ),
    ]
